name: 🚀 编译 (Build)

on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'ImmortalWrt 仓库的拥有者 (Owner of ImmortalWrt repo)'
        type: string
        required: true
        default: 'immortalwrt'
      repo:
        description: 'ImmortalWrt 仓库的名字 (Name of ImmortalWrt repo)'
        type: string
        required: true
        default: 'immortalwrt'
      branch:
        description: 'ImmortalWrt 仓库的分支 (Branch of ImmortalWrt repo)'
        type: string
        required: true
        default: 'openwrt-23.05'
      tag:
        description: 'The tag to checkout'
        required: true
        default: 'v23.05.3'
      multithreading:
        description: '开启多线程编译 (Enable multithreading build)'
        type: boolean
        default: true
      ssh:
        description: '使用 ssh 连接到编译环境 (Connect to the build environment using ssh)'
        type: boolean
        default: false

jobs:
  build:
    if: ${{inputs.ssh == false}}
    runs-on: ubuntu-latest
    name: 🚀 编译 (Build)
    steps:
      - name: 下载编译所需的依赖 (Install the software packages required for compilation)
        run: |
          sudo apt update
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

      - name: 克隆当前仓库 (Clone current repo)
        uses: actions/checkout@v4

      - name: 克隆 ImmortalWrt 仓库 (Clone ImmortalWrt repo)
        uses: actions/checkout@v4
        with:
          repository: '${{inputs.owner}}/${{inputs.repo}}'
          ref: 'refs/tags/${{inputs.tag}}'
          path: ImmortalWrt

      - name: 释放磁盘空间 (Free disk space)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: 复制当前仓库的配置文件到 ImmortalWrt 仓库  (Copy current repo config to ImmortalWrt repo)
        run: cp -f .config feeds.conf.default diy.sh ImmortalWrt/

      - name: 运行 diy.sh (Run diy.sh)
        working-directory: ImmortalWrt
        run: |
          chmod +x diy.sh
          ./diy.sh

      - name: 更新并下载 feeds (Update and download feeds)
        working-directory: ImmortalWrt
        run: ./scripts/feeds update -a && ./scripts/feeds install -a

      - name: 再次复制当前仓库的配置文件到 ImmortalWrt 仓库 (Copy current repo config to ImmortalWrt repo again)
        run: cp -f .config feeds.conf.default diy.sh ImmortalWrt/

      - name: 编译前上传配置 (Upload config before build)
        uses: actions/upload-artifact@v4
        with:
          name: config-before-build
          path: ImmortalWrt/.config

      - name: 编译前上传Feeds (Upload feeds before build)
        uses: actions/upload-artifact@v4
        with:
          name: feeds-before-build
          path: ImmortalWrt/feeds.conf.default

      - name: 多线程编译 ImmortalWrt (Build ImmortalWrt multithreading)
        if: ${{inputs.multithreading == true}}
        working-directory: ImmortalWrt
        run: make -j$(nproc) V=s

      - name: 单线程编译 ImmortalWrt (Build ImmortalWrt single thread)
        if: ${{inputs.multithreading == false}}
        working-directory: ImmortalWrt
        run: make -j1 V=s

      - name: 上传编译结果到 Artifact (Upload build result to Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt-build-result
          path: ImmortalWrt/bin/targets

  build-ssh:
    if: ${{inputs.ssh == true}}
    name: 🚀 编译 (Build) - SSH
    runs-on: ubuntu-latest
    steps:
      - name: 下载编译所需的依赖 (Install the software packages required for compilation)
        run: |
          sudo apt update
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

      - name: 克隆当前仓库 (Clone current repo)
        uses: actions/checkout@v4

      - name: 克隆 ImmortalWrt 仓库 (Clone ImmortalWrt repo)
        uses: actions/checkout@v4
        with:
          repository: '${{inputs.owner}}/${{inputs.repo}}'
          ref: 'refs/tags/${{inputs.tag}}'
          path: ImmortalWrt

      - name: 开启 SSH 服务 (Start SSH service)
        uses: lhotari/action-upterm@v1
        with:
          wait-timeout-minutes: 3

      - name: 编译前上传配置 (Upload config before build)
        uses: actions/upload-artifact@v4
        with:
          name: config-before-build
          path: ImmortalWrt/.config

      - name: 编译前上传Feeds (Upload feeds before build)
        uses: actions/upload-artifact@v4
        with:
          name: feeds-before-build
          path: ImmortalWrt/feeds.conf.default

      - name: 多线程编译 ImmortalWrt (Build ImmortalWrt multithreading)
        if: ${{inputs.multithreading == true}}
        working-directory: ImmortalWrt
        run: make -j$(nproc) V=s

      - name: 单线程编译 ImmortalWrt (Build ImmortalWrt single thread)
        if: ${{inputs.multithreading == false}}
        working-directory: ImmortalWrt
        run: make -j1 V=s

      - name: 上传编译结果到 Artifact (Upload build result to Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt-build-result
          path: ImmortalWrt/bin/targets
          
      - name: 编译后上传配置到 Artifact (Upload build config to Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt-build-config
          path: ImmortalWrt/.config
